### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by dee12452** [zeldin/SDL_PSL1GHT_Libs#4]
Hi,

I'm trying to look into this issue (https://github.com/ps3dev/ps3toolchain/issues/95) I posted on the ps3toolchain repo locally inside my own ubuntu docker container. I've created a fresh container with what I thought was the basic necessities
```
  apt-get -y install \
  autoconf bison build-essential ca-certificates flex git libelf-dev\
  libgmp-dev libncurses5-dev libssl-dev libtool-bin pkg-config python-dev \
  texinfo wget zlib1g-dev
```

But when I run `sh make_SDL_Libs.sh` I am getting
```
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/build/SDL_gfx-2.0.22':
configure: error: C compiler cannot create executables
See `config.log' for more details.
scripts/000_SDL_gfx-2.0.22.sh: Failed.
```

I've tried using alpine:3.7 instead and same thing there. Am I missing something I need to setup?

**Comment by dee12452** [comment]
Ok it looks as though the issue is that the docker container I'm using hasn't setup psl1ght, and doesn't have the $PS3DEV/portlibs/ppu folder setup. However that still doesn't resolve the original issue when trying to run the toolchain in the container
```
effect_position.c:33:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
make: *** [build/effect_position.lo] Error 1
Makefile:137: recipe for target 'build/effect_position.lo' failed
scripts/005_SDL2_mixer-2.0.4.sh: Failed.
../scripts/014-sdl_psl1ght_libs.sh: Failed.
../scripts/009-ps3libraries.sh: Failed.
The command '/bin/sh -c /build/toolchain.sh' returned a non-zero code: 1
```

**Comment by zeldin** [comment]
Looks like #3 requires SDL2 to be built first.  I've reverted the build of SDL2_mixer for now.
